name: cron-job

on:
  schedule:
    - cron: '0 8 * * *'
  
  workflow_dispatch:
  
jobs:
  executar-tarefa:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v4

      - name: node config
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install and run
        run: |
          npm install
          node script.js
